import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import { z } from 'zod';

import {
  AgentKnowledgeSchema,
  AgentSchema,
  AgentTurnInputSchema,
  AgentTurnOutputSchema,
  BeliefUpdateSchema,
  ClaimSchema,
  ExpeditionFixtureSchema,
  ExpeditionSchema,
  ForecastCommitSchema,
  MarketSchema,
  MeetingSchema,
  MissionSchema,
  ProfessorQuerySchema,
  ProfessorResponseSchema,
  SignalSchema,
  SourceRecordSchema,
  WorldCommandSchema,
  WorldEventSchema,
  WorldManifestSchema,
} from '../src/index.js';

const GENERATED_COMMENT =
  'Generated by @signal-atlas/contracts. Edit the Zod source and rerun pnpm --filter @signal-atlas/contracts generate:schemas.';

export const schemaDirectory = fileURLToPath(new URL('../../../schemas/', import.meta.url));

const schemas = {
  'agent-knowledge.schema.json': AgentKnowledgeSchema,
  'agent-state.schema.json': AgentSchema,
  'agent-turn-input.schema.json': AgentTurnInputSchema,
  'agent-turn-output.schema.json': AgentTurnOutputSchema,
  'belief-update.schema.json': BeliefUpdateSchema,
  'claim.schema.json': ClaimSchema,
  'expedition-fixture.schema.json': ExpeditionFixtureSchema,
  'expedition.schema.json': ExpeditionSchema,
  'forecast-commit.schema.json': ForecastCommitSchema,
  'market.schema.json': MarketSchema,
  'meeting.schema.json': MeetingSchema,
  'mission.schema.json': MissionSchema,
  'professor-query.schema.json': ProfessorQuerySchema,
  'professor-response.schema.json': ProfessorResponseSchema,
  'signal.schema.json': SignalSchema,
  'source-record.schema.json': SourceRecordSchema,
  'world-command.schema.json': WorldCommandSchema,
  'world-event.schema.json': WorldEventSchema,
  'world-manifest.schema.json': WorldManifestSchema,
} satisfies Record<string, z.ZodType>;

function sortObjectKeys(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(sortObjectKeys);
  }
  if (value !== null && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, child]) => [key, sortObjectKeys(child)]),
    );
  }
  return value;
}

function renderSchema(filename: string, schema: z.ZodType): string {
  const generated = z.toJSONSchema(schema, {
    reused: 'ref',
    target: 'draft-2020-12',
  });
  const document = sortObjectKeys({
    ...generated,
    $comment: GENERATED_COMMENT,
    $id: `https://signal-atlas.local/schemas/${filename}`,
  });
  return `${JSON.stringify(document, null, 2)}\n`;
}

export function renderSchemaArtifacts(): ReadonlyMap<string, string> {
  return new Map(
    Object.entries(schemas).map(([filename, schema]) => [filename, renderSchema(filename, schema)]),
  );
}

async function checkArtifacts(artifacts: ReadonlyMap<string, string>): Promise<void> {
  const stale: string[] = [];
  for (const [filename, expected] of artifacts) {
    const path = `${schemaDirectory}${filename}`;
    const actual = await readFile(path, 'utf8').catch(() => undefined);
    if (actual !== expected) {
      stale.push(filename);
    }
  }
  if (stale.length > 0) {
    throw new Error(
      `Generated JSON Schemas are missing or stale: ${stale.join(', ')}. Run the schema generator.`,
    );
  }
}

async function writeArtifacts(artifacts: ReadonlyMap<string, string>): Promise<void> {
  await Promise.all(
    [...artifacts].map(([filename, contents]) =>
      writeFile(`${schemaDirectory}${filename}`, contents, 'utf8'),
    ),
  );
}

async function main(): Promise<void> {
  const artifacts = renderSchemaArtifacts();
  if (process.argv.includes('--check')) {
    await checkArtifacts(artifacts);
    process.stdout.write(`Verified ${artifacts.size} generated JSON Schemas.\n`);
    return;
  }
  await writeArtifacts(artifacts);
  process.stdout.write(`Generated ${artifacts.size} JSON Schemas.\n`);
}

const invokedPath = process.argv[1];
if (invokedPath && fileURLToPath(import.meta.url) === invokedPath) {
  await main();
}
