import { ExpeditionEventStream } from '../world-shell/event-stream-client.js';
import {
  createClientId,
  createExpedition,
  disconnectPrefConnection,
  fetchCaseFile,
  fetchExpeditionEvents,
  fetchExpeditions,
  fetchExpeditionSnapshot,
  fetchFixtureConfiguration,
  fetchPrefDiagnostics,
  fetchReplayProjection,
  fetchRuntimeDiagnostics,
  fetchScenarios,
  interpretMissionDraft,
  resolveFixtureCase,
  submitWorldCommand,
  testPrefConnection,
  updateFixtureMissionScenario,
} from '../world-shell/runtime-client.js';
import type { RuntimePort } from './runtime-port.js';

export const remoteRuntime: RuntimePort = {
  kind: 'remote',
  supportsConnectionControls: true,
  createClientId,
  fetchExpeditions,
  fetchScenarios,
  createExpedition,
  fetchExpeditionSnapshot,
  fetchRuntimeDiagnostics,
  fetchPrefDiagnostics,
  testPrefConnection,
  disconnectPrefConnection,
  fetchExpeditionEvents,
  fetchReplayProjection,
  resolveFixtureCase,
  fetchCaseFile,
  fetchFixtureConfiguration,
  updateFixtureMissionScenario,
  interpretMissionDraft,
  submitWorldCommand,
  createEventSubscription: (options) => new ExpeditionEventStream(options),
};
